AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless backend for the restaurant shift tracker

Resources:
  CreateShiftFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/create_shift/
      Handler: create_shift.lambda_handler
      Runtime: python3.14
